# Generated by Django 5.2.1 on 2025-05-26 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="bulletin",
        ),
        migrations.AddField(
            model_name="review",
            name="bulletin",
            field=models.ForeignKey(
                default=10,
                help_text="Объявление, под которым оставлен отзыв",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="bulletin.bulletin",
                verbose_name="Объявление",
            ),
            preserve_default=False,
        ),
    ]
