# Generated by Django 5.2.1 on 2025-05-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("user", "Пользователь"), ("admin", "Администратор")],
                default="user",
                help_text="Укажите вашу роль",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
