# Generated by Django 5.2.1 on 2025-06-01 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата регистрации"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now, verbose_name="Последний вход"
            ),
            preserve_default=False,
        ),
    ]
